data:
  image: busybox
  volumes:
   - /cybrain:/cybrain

cython:
  image: cgarciae/cython:0.23.4
  volumes_from:
    - data
    
tensorflow:
  image: b.gcr.io/tensorflow/tensorflow
  volumes_from:
    - data
  
